"""Dump the most-recent GameForge project to a human-readable Markdown gallery.

Reads scripts/smoke_full_pipeline.state.json (or the path passed via
--state) and writes docs/GAME_GALLERY.md with:

  - concept (title, setting, mood, mechanics, art style)
  - world (regions, dungeons, lore)
  - sample items, quests, NPCs
  - art style guide
  - QA report (issues + verdict)

Usage:
    py scripts/dump_game_gallery.py

Designed so Kruz can wake up, open docs/GAME_GALLERY.md, and read what
the agent team built overnight without ever opening Godot.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))


def _render(project: dict) -> str:
    """Produce a single Markdown blob from a project dict."""
    lines: list[str] = []
    L = lines.append

    concept = project.get("concept") or {}
    world = project.get("world") or {}
    items = project.get("items") or []
    quests = project.get("quests") or []
    npcs = project.get("npcs") or []
    style = project.get("style_guide") or {}
    qa = project.get("qa_report") or {}

    title = concept.get("title", "Untitled")
    genre = concept.get("genre", "?")

    L(f"# GameForge Output — {title}")
    L("")
    L(f"_Auto-generated by `scripts/dump_game_gallery.py`._")
    L("")
    L(f"**Genre:** {genre}  ")
    L(f"**Items:** {len(items)}  **Quests:** {len(quests)}  "
      f"**NPCs:** {len(npcs)}  ")
    L(f"**Style guide:** {'present' if style else 'missing'}  "
      f"**QA verdict:** {'playable' if qa.get('playable') else 'not playable'}  "
      f"({len(qa.get('issues', []))} issues)")
    L("")
    L("---")
    L("")

    # CONCEPT
    L("## Concept")
    L("")
    L(f"**Setting** — {concept.get('setting', '')}")
    L("")
    L(f"**Mood** — {concept.get('target_mood', '')}")
    L("")
    L(f"**Art style** — {concept.get('art_style', '')}")
    L("")
    L("**Core mechanics:**")
    for m in concept.get("core_mechanics") or []:
        L(f"  - {m}")
    L("")

    # WORLD
    L("## World")
    L("")
    L(f"**Name** — {world.get('name', '')}")
    L("")
    L(f"**Description** — {world.get('description', '')}")
    L("")
    lore = (world.get("lore_summary") or "").strip()
    if lore:
        L("**Lore:**")
        L(f"> {lore}")
        L("")
    overworld = world.get("overworld") or {}
    regions = overworld.get("regions") or []
    if regions:
        L(f"### Regions ({len(regions)})")
        L("")
        for r in regions:
            L(f"- **{r.get('name', '?')}** "
              f"({r.get('biome', '?')}, "
              f"levels {r.get('level_range', [])}) — "
              f"{(r.get('description') or '')[:160]}")
        L("")
    dungeons = world.get("dungeons") or []
    if dungeons:
        L(f"### Dungeons ({len(dungeons)})")
        L("")
        for d in dungeons[:5]:
            L(f"- **{d.get('name', '?')}** — "
              f"{(d.get('description') or '')[:160]}")
        L("")

    # ITEMS (top 6)
    if items:
        L(f"## Items ({len(items)} total — first 6)")
        L("")
        for it in items[:6]:
            L(f"### {it.get('name', '?')}")
            L(f"_{it.get('item_type', '?')}_  ·  "
              f"{(it.get('description') or '')}")
            stats = it.get("stats")
            if stats:
                L(f"  - stats: {stats}")
            L("")

    # QUESTS (top 4)
    if quests:
        L(f"## Quests ({len(quests)} total — first 4)")
        L("")
        for q in quests[:4]:
            L(f"### {q.get('name', '?')}")
            L(f"_{q.get('quest_type', '?')}_")
            L("")
            L(f"{(q.get('description') or '')}")
            objs = q.get("objectives") or []
            if objs:
                L("")
                L("**Objectives:**")
                for o in objs:
                    L(f"  - {o.get('description', '?')}")
            L("")

    # NPCs (top 4)
    if npcs:
        L(f"## NPCs ({len(npcs)} total — first 4)")
        L("")
        for n in npcs[:4]:
            L(f"### {n.get('name', '?')}")
            L(f"_{n.get('disposition', '?')}_  ·  "
              f"role: {n.get('role', '?')}")
            L("")
            L(f"{(n.get('description') or '')}")
            L("")

    # STYLE GUIDE
    if style:
        L("## Art Style Guide")
        L("")
        L(f"**Overall** — {style.get('overall_aesthetic', '')}")
        L("")
        palette = style.get("color_palette")
        if palette:
            L("**Palette:**")
            if isinstance(palette, dict):
                for k, v in palette.items():
                    L(f"  - {k}: `{v}`")
            elif isinstance(palette, list):
                for entry in palette[:12]:
                    if isinstance(entry, dict):
                        # e.g. {"name": "...", "hex": "#aabbcc"}
                        label = entry.get("name") or entry.get("role") or "color"
                        value = entry.get("hex") or entry.get("value") or str(entry)
                        L(f"  - {label}: `{value}`")
                    else:
                        L(f"  - `{entry}`")
            L("")

    # QA REPORT
    if qa:
        L("## QA Report")
        L("")
        L(f"**Verdict:** {'playable' if qa.get('playable') else 'NOT playable'}  ·  "
          f"**Score:** {qa.get('overall_score', '?')}/10")
        L("")
        summary = qa.get("summary") or ""
        if summary:
            L(f"> {summary}")
            L("")
        issues = qa.get("issues") or []
        if issues:
            L(f"### Issues found ({len(issues)})")
            L("")
            for i, issue in enumerate(issues[:12], 1):
                sev = issue.get("severity", "?")
                desc = issue.get("description", "?")
                L(f"{i}. **[{sev}]** {desc}")
            L("")

    L("---")
    L("")
    L("_Regenerate this gallery by running:_")
    L("```")
    L("py scripts/dump_game_gallery.py")
    L("```")
    L("")
    L("_Generate a fresh project (~4.5 min, ~$1.50):_")
    L("```")
    L("py scripts/smoke_full_pipeline.py")
    L("```")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--state",
        default=str(HERE / "smoke_full_pipeline.state.json"),
        help="path to the saved GameProject JSON",
    )
    ap.add_argument(
        "--out",
        default=str(ROOT / "docs" / "GAME_GALLERY.md"),
        help="destination Markdown file",
    )
    args = ap.parse_args()

    state_path = Path(args.state)
    if not state_path.exists():
        print(f"FAIL: no state file at {state_path}")
        print("  Run scripts/smoke_full_pipeline.py first.")
        return 1
    project = json.loads(state_path.read_text(encoding="utf-8"))
    md = _render(project)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(f"OK: wrote {len(md)} bytes to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
